# generated by datamodel-codegen:
#   filename:  ApplyPatchApprovalParams.json
#   timestamp: 2026-05-24T05:49:29+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class Type(Enum):
    add = 'add'


class FileChange1(BaseModel):
    content: str
    type: Type = Field(..., title='AddFileChangeType')


class Type1(Enum):
    delete = 'delete'


class FileChange2(BaseModel):
    content: str
    type: Type1 = Field(..., title='DeleteFileChangeType')


class Type2(Enum):
    update = 'update'


class FileChange3(BaseModel):
    move_path: str | None = None
    type: Type2 = Field(..., title='UpdateFileChangeType')
    unified_diff: str


class FileChange(RootModel[FileChange1 | FileChange2 | FileChange3]):
    root: FileChange1 | FileChange2 | FileChange3


class ThreadId(RootModel[str]):
    root: str


class ApplyPatchApprovalParams(BaseModel):
    callId: str = Field(
        ...,
        description='Use to correlate this with [codex_protocol::protocol::PatchApplyBeginEvent] and [codex_protocol::protocol::PatchApplyEndEvent].',
    )
    conversationId: ThreadId
    fileChanges: dict[str, FileChange]
    grantRoot: str | None = Field(
        None,
        description='When set, the agent is asking the user to allow writes under this root for the remainder of the session (unclear if this is honored today).',
    )
    reason: str | None = Field(
        None,
        description='Optional explanatory reason (e.g. request for extra write access).',
    )
