# generated by datamodel-codegen:
#   filename:  AttestationGenerateResponse.json
#   timestamp: 2026-05-24T05:49:37+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class AttestationGenerateResponse(BaseModel):
    token: str = Field(..., description='Opaque client attestation token.')
