# generated by datamodel-codegen:
#   filename:  AttestationGenerateParams.json
#   timestamp: 2026-05-24T05:49:36+00:00

from __future__ import annotations

from pydantic import BaseModel


class AttestationGenerateParams(BaseModel):
    pass
