# generated by datamodel-codegen:
#   filename:  ChatgptAuthTokensRefreshResponse.json
#   timestamp: 2026-05-24T05:49:39+00:00

from __future__ import annotations

from pydantic import BaseModel


class ChatgptAuthTokensRefreshResponse(BaseModel):
    accessToken: str
    chatgptAccountId: str
    chatgptPlanType: str | None = None
