# generated by datamodel-codegen:
#   filename:  ChatgptAuthTokensRefreshParams.json
#   timestamp: 2026-05-24T05:49:38+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class ChatgptAuthTokensRefreshReason1(Enum):
    unauthorized = 'unauthorized'


class ChatgptAuthTokensRefreshReason(RootModel[ChatgptAuthTokensRefreshReason1]):
    root: ChatgptAuthTokensRefreshReason1


class ChatgptAuthTokensRefreshParams(BaseModel):
    previousAccountId: str | None = Field(
        None,
        description='Workspace/account identifier that Codex was previously using.\n\nClients that manage multiple accounts/workspaces can use this as a hint to refresh the token for the correct workspace.\n\nThis may be `null` when the prior auth state did not include a workspace identifier (`chatgpt_account_id`).',
    )
    reason: ChatgptAuthTokensRefreshReason
