# generated by datamodel-codegen:
#   filename:  ClientNotification.json
#   timestamp: 2026-05-24T05:49:40+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class Method(Enum):
    initialized = 'initialized'


class ClientNotification1(BaseModel):
    method: Method = Field(..., title='InitializedNotificationMethod')


class ClientNotification(RootModel[ClientNotification1]):
    root: ClientNotification1 = Field(..., title='ClientNotification')
