# generated by datamodel-codegen:
#   filename:  ClientRequest.json
#   timestamp: 2026-05-24T05:49:42+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class Method(Enum):
    initialize = 'initialize'


class Method1(Enum):
    thread_start = 'thread/start'


class Method2(Enum):
    thread_resume = 'thread/resume'


class Method3(Enum):
    thread_fork = 'thread/fork'


class Method4(Enum):
    thread_archive = 'thread/archive'


class Method5(Enum):
    thread_unsubscribe = 'thread/unsubscribe'


class Method6(Enum):
    thread_name_set = 'thread/name/set'


class Method7(Enum):
    thread_goal_set = 'thread/goal/set'


class Method8(Enum):
    thread_goal_get = 'thread/goal/get'


class Method9(Enum):
    thread_goal_clear = 'thread/goal/clear'


class Method10(Enum):
    thread_metadata_update = 'thread/metadata/update'


class Method11(Enum):
    thread_unarchive = 'thread/unarchive'


class Method12(Enum):
    thread_compact_start = 'thread/compact/start'


class Method13(Enum):
    thread_shellCommand = 'thread/shellCommand'


class Method14(Enum):
    thread_approveGuardianDeniedAction = 'thread/approveGuardianDeniedAction'


class Method15(Enum):
    thread_rollback = 'thread/rollback'


class Method16(Enum):
    thread_list = 'thread/list'


class Method17(Enum):
    thread_loaded_list = 'thread/loaded/list'


class Method18(Enum):
    thread_read = 'thread/read'


class Method19(Enum):
    thread_inject_items = 'thread/inject_items'


class Method20(Enum):
    skills_list = 'skills/list'


class Method21(Enum):
    hooks_list = 'hooks/list'


class Method22(Enum):
    marketplace_add = 'marketplace/add'


class Method23(Enum):
    marketplace_remove = 'marketplace/remove'


class Method24(Enum):
    marketplace_upgrade = 'marketplace/upgrade'


class Method25(Enum):
    plugin_list = 'plugin/list'


class Method26(Enum):
    plugin_installed = 'plugin/installed'


class Method27(Enum):
    plugin_read = 'plugin/read'


class Method28(Enum):
    plugin_skill_read = 'plugin/skill/read'


class Method29(Enum):
    plugin_share_save = 'plugin/share/save'


class Method30(Enum):
    plugin_share_updateTargets = 'plugin/share/updateTargets'


class Method31(Enum):
    plugin_share_list = 'plugin/share/list'


class Method32(Enum):
    plugin_share_checkout = 'plugin/share/checkout'


class Method33(Enum):
    plugin_share_delete = 'plugin/share/delete'


class Method34(Enum):
    app_list = 'app/list'


class Method35(Enum):
    fs_readFile = 'fs/readFile'


class Method36(Enum):
    fs_writeFile = 'fs/writeFile'


class Method37(Enum):
    fs_createDirectory = 'fs/createDirectory'


class Method38(Enum):
    fs_getMetadata = 'fs/getMetadata'


class Method39(Enum):
    fs_readDirectory = 'fs/readDirectory'


class Method40(Enum):
    fs_remove = 'fs/remove'


class Method41(Enum):
    fs_copy = 'fs/copy'


class Method42(Enum):
    fs_watch = 'fs/watch'


class Method43(Enum):
    fs_unwatch = 'fs/unwatch'


class Method44(Enum):
    skills_config_write = 'skills/config/write'


class Method45(Enum):
    plugin_install = 'plugin/install'


class Method46(Enum):
    plugin_uninstall = 'plugin/uninstall'


class Method47(Enum):
    turn_start = 'turn/start'


class Method48(Enum):
    turn_steer = 'turn/steer'


class Method49(Enum):
    turn_interrupt = 'turn/interrupt'


class Method50(Enum):
    review_start = 'review/start'


class Method51(Enum):
    model_list = 'model/list'


class Method52(Enum):
    modelProvider_capabilities_read = 'modelProvider/capabilities/read'


class Method53(Enum):
    experimentalFeature_list = 'experimentalFeature/list'


class Method54(Enum):
    permissionProfile_list = 'permissionProfile/list'


class Method55(Enum):
    experimentalFeature_enablement_set = 'experimentalFeature/enablement/set'


class Method56(Enum):
    mcpServer_oauth_login = 'mcpServer/oauth/login'


class Method57(Enum):
    config_mcpServer_reload = 'config/mcpServer/reload'


class Method58(Enum):
    mcpServerStatus_list = 'mcpServerStatus/list'


class Method59(Enum):
    mcpServer_resource_read = 'mcpServer/resource/read'


class Method60(Enum):
    mcpServer_tool_call = 'mcpServer/tool/call'


class Method61(Enum):
    windowsSandbox_setupStart = 'windowsSandbox/setupStart'


class Method62(Enum):
    windowsSandbox_readiness = 'windowsSandbox/readiness'


class Method63(Enum):
    account_login_start = 'account/login/start'


class Method64(Enum):
    account_login_cancel = 'account/login/cancel'


class Method65(Enum):
    account_logout = 'account/logout'


class Method66(Enum):
    account_rateLimits_read = 'account/rateLimits/read'


class Method67(Enum):
    account_sendAddCreditsNudgeEmail = 'account/sendAddCreditsNudgeEmail'


class Method68(Enum):
    feedback_upload = 'feedback/upload'


class Method69(Enum):
    command_exec = 'command/exec'


class Method70(Enum):
    command_exec_write = 'command/exec/write'


class Method71(Enum):
    command_exec_terminate = 'command/exec/terminate'


class Method72(Enum):
    command_exec_resize = 'command/exec/resize'


class Method73(Enum):
    config_read = 'config/read'


class Method74(Enum):
    externalAgentConfig_detect = 'externalAgentConfig/detect'


class Method75(Enum):
    externalAgentConfig_import = 'externalAgentConfig/import'


class Method76(Enum):
    config_value_write = 'config/value/write'


class Method77(Enum):
    config_batchWrite = 'config/batchWrite'


class Method78(Enum):
    configRequirements_read = 'configRequirements/read'


class Method79(Enum):
    account_read = 'account/read'


class Method80(Enum):
    fuzzyFileSearch = 'fuzzyFileSearch'


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class AddCreditsNudgeCreditType(Enum):
    credits = 'credits'
    usage_limit = 'usage_limit'


class ApprovalsReviewer(Enum):
    user = 'user'
    auto_review = 'auto_review'
    guardian_subagent = 'guardian_subagent'


class AppsListParams(BaseModel):
    cursor: str | None = Field(
        None, description='Opaque pagination cursor returned by a previous call.'
    )
    forceRefetch: bool | None = Field(
        None,
        description='When true, bypass app caches and fetch the latest data from sources.',
    )
    limit: conint(ge=0) | None = Field(
        None,
        description='Optional page size; defaults to a reasonable server-side value.',
    )
    threadId: str | None = Field(
        None,
        description="Optional thread id used to evaluate app feature gating from that thread's config.",
    )


class AskForApproval1(Enum):
    untrusted = 'untrusted'
    on_failure = 'on-failure'
    on_request = 'on-request'
    never = 'never'


class Granular(BaseModel):
    mcp_elicitations: bool
    request_permissions: bool | None = False
    rules: bool
    sandbox_approval: bool
    skill_approval: bool | None = False


class AskForApproval2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    granular: Granular


class AskForApproval(RootModel[AskForApproval1 | AskForApproval2]):
    root: AskForApproval1 | AskForApproval2


class ByteRange(BaseModel):
    end: conint(ge=0)
    start: conint(ge=0)


class CancelLoginAccountParams(BaseModel):
    loginId: str


class ClientInfo(BaseModel):
    name: str
    title: str | None = None
    version: str


class CommandExecTerminalSize(BaseModel):
    cols: conint(ge=0) = Field(..., description='Terminal width in character cells.')
    rows: conint(ge=0) = Field(..., description='Terminal height in character cells.')


class CommandExecTerminateParams(BaseModel):
    processId: str = Field(
        ...,
        description='Client-supplied, connection-scoped `processId` from the original `command/exec` request.',
    )


class CommandExecWriteParams(BaseModel):
    closeStdin: bool | None = Field(
        None, description='Close stdin after writing `deltaBase64`, if present.'
    )
    deltaBase64: str | None = Field(
        None, description='Optional base64-encoded stdin bytes to write.'
    )
    processId: str = Field(
        ...,
        description='Client-supplied, connection-scoped `processId` from the original `command/exec` request.',
    )


class CommandMigration(BaseModel):
    name: str


class ConfigReadParams(BaseModel):
    cwd: str | None = Field(
        None,
        description='Optional working directory to resolve project config layers. If specified, return the effective config as seen from that directory (i.e., including any project layers between `cwd` and the project/repo root).',
    )
    includeLayers: bool | None = False


class Type(Enum):
    input_text = 'input_text'


class ContentItem1(BaseModel):
    text: str
    type: Type = Field(..., title='InputTextContentItemType')


class Type1(Enum):
    input_image = 'input_image'


class Type2(Enum):
    output_text = 'output_text'


class ContentItem3(BaseModel):
    text: str
    type: Type2 = Field(..., title='OutputTextContentItemType')


class DynamicToolSpec(BaseModel):
    deferLoading: bool | None = None
    description: str
    inputSchema: Any
    name: str
    namespace: str | None = None


class WindowsSandboxSetupMode(Enum):
    elevated = 'elevated'
    unelevated = 'unelevated'


class ExperimentalFeatureEnablementSetParams(BaseModel):
    enablement: dict[str, bool] = Field(
        ...,
        description='Process-wide runtime feature enablement keyed by canonical feature name.\n\nOnly named features are updated. Omitted features are left unchanged. Send an empty map for a no-op.',
    )


class ExperimentalFeatureListParams(BaseModel):
    cursor: str | None = Field(
        None, description='Opaque pagination cursor returned by a previous call.'
    )
    limit: conint(ge=0) | None = Field(
        None,
        description='Optional page size; defaults to a reasonable server-side value.',
    )
    threadId: str | None = Field(
        None,
        description="Optional loaded thread id. Pass this when showing feature state for an existing thread so enablement is computed from that thread's refreshed config, including project-local config for the thread's cwd.",
    )


class ExternalAgentConfigDetectParams(BaseModel):
    cwds: list[str] | None = Field(
        None,
        description='Zero or more working directories to include for repo-scoped detection.',
    )
    includeHome: bool | None = Field(
        None,
        description="If true, include detection under the user's home (~/.claude, ~/.codex, etc.).",
    )


class ExternalAgentConfigMigrationItemType(Enum):
    AGENTS_MD = 'AGENTS_MD'
    CONFIG = 'CONFIG'
    SKILLS = 'SKILLS'
    PLUGINS = 'PLUGINS'
    MCP_SERVER_CONFIG = 'MCP_SERVER_CONFIG'
    SUBAGENTS = 'SUBAGENTS'
    HOOKS = 'HOOKS'
    COMMANDS = 'COMMANDS'
    SESSIONS = 'SESSIONS'


class FeedbackUploadParams(BaseModel):
    classification: str
    extraLogFiles: list[str] | None = None
    includeLogs: bool
    reason: str | None = None
    tags: dict[str, Any] | None = None
    threadId: str | None = None


class FsCopyParams(BaseModel):
    destinationPath: AbsolutePathBuf = Field(
        ..., description='Absolute destination path.'
    )
    recursive: bool | None = Field(
        None, description='Required for directory copies; ignored for file copies.'
    )
    sourcePath: AbsolutePathBuf = Field(..., description='Absolute source path.')


class FsCreateDirectoryParams(BaseModel):
    path: AbsolutePathBuf = Field(..., description='Absolute directory path to create.')
    recursive: bool | None = Field(
        None,
        description='Whether parent directories should also be created. Defaults to `true`.',
    )


class FsGetMetadataParams(BaseModel):
    path: AbsolutePathBuf = Field(..., description='Absolute path to inspect.')


class FsReadDirectoryParams(BaseModel):
    path: AbsolutePathBuf = Field(..., description='Absolute directory path to read.')


class FsReadFileParams(BaseModel):
    path: AbsolutePathBuf = Field(..., description='Absolute path to read.')


class FsRemoveParams(BaseModel):
    force: bool | None = Field(
        None, description='Whether missing paths should be ignored. Defaults to `true`.'
    )
    path: AbsolutePathBuf = Field(..., description='Absolute path to remove.')
    recursive: bool | None = Field(
        None,
        description='Whether directory removal should recurse. Defaults to `true`.',
    )


class FsUnwatchParams(BaseModel):
    watchId: str = Field(
        ..., description='Watch identifier previously provided to `fs/watch`.'
    )


class FsWatchParams(BaseModel):
    path: AbsolutePathBuf = Field(
        ..., description='Absolute file or directory path to watch.'
    )
    watchId: str = Field(
        ...,
        description='Connection-scoped watch identifier used for `fs/unwatch` and `fs/changed`.',
    )


class FsWriteFileParams(BaseModel):
    dataBase64: str = Field(..., description='File contents encoded as base64.')
    path: AbsolutePathBuf = Field(..., description='Absolute path to write.')


class Type3(Enum):
    input_text = 'input_text'


class FunctionCallOutputContentItem1(BaseModel):
    text: str
    type: Type3 = Field(..., title='InputTextFunctionCallOutputContentItemType')


class Type4(Enum):
    input_image = 'input_image'


class Type5(Enum):
    encrypted_content = 'encrypted_content'


class FunctionCallOutputContentItem3(BaseModel):
    encrypted_content: str
    type: Type5 = Field(..., title='EncryptedContentFunctionCallOutputContentItemType')


class FuzzyFileSearchParams(BaseModel):
    cancellationToken: str | None = None
    query: str
    roots: list[str]


class Type6(Enum):
    text = 'text'


class Type7(Enum):
    image = 'image'


class Type8(Enum):
    localImage = 'localImage'


class Type9(Enum):
    skill = 'skill'


class UserInput4(BaseModel):
    name: str
    path: str
    type: Type9 = Field(..., title='SkillUserInputType')


class Type10(Enum):
    mention = 'mention'


class UserInput5(BaseModel):
    name: str
    path: str
    type: Type10 = Field(..., title='MentionUserInputType')


class GetAccountParams(BaseModel):
    refreshToken: bool | None = Field(
        False,
        description='When `true`, requests a proactive token refresh before returning.\n\nIn managed auth mode this triggers the normal refresh-token flow. In external auth mode this flag is ignored. Clients should refresh tokens themselves and call `account/login/start` with `chatgptAuthTokens`.',
    )


class HookMigration(BaseModel):
    name: str


class HooksListParams(BaseModel):
    cwds: list[str] | None = Field(
        None,
        description='When empty, defaults to the current session working directory.',
    )


class ImageDetail(Enum):
    high = 'high'
    original = 'original'


class InitializeCapabilities(BaseModel):
    experimentalApi: bool | None = Field(
        False, description='Opt into receiving experimental API methods and fields.'
    )
    optOutNotificationMethods: list[str] | None = Field(
        None,
        description='Exact notification method names that should be suppressed for this connection (for example `thread/started`).',
    )
    requestAttestation: bool | None = Field(
        False,
        description='Opt into `attestation/generate` requests for upstream `x-oai-attestation`.',
    )


class InitializeParams(BaseModel):
    capabilities: InitializeCapabilities | None = None
    clientInfo: ClientInfo


class Type11(Enum):
    exec = 'exec'


class LocalShellAction1(BaseModel):
    command: list[str]
    env: dict[str, Any] | None = None
    timeout_ms: conint(ge=0) | None = None
    type: Type11 = Field(..., title='ExecLocalShellActionType')
    user: str | None = None
    working_directory: str | None = None


class LocalShellAction(RootModel[LocalShellAction1]):
    root: LocalShellAction1


class LocalShellStatus(Enum):
    completed = 'completed'
    in_progress = 'in_progress'
    incomplete = 'incomplete'


class Type12(Enum):
    apiKey = 'apiKey'


class LoginAccountParams1(BaseModel):
    apiKey: str
    type: Type12 = Field(..., title='ApiKeyLoginAccountParamsType')


class Type13(Enum):
    chatgpt = 'chatgpt'


class LoginAccountParams2(BaseModel):
    codexStreamlinedLogin: bool | None = None
    type: Type13 = Field(..., title='ChatgptLoginAccountParamsType')


class Type14(Enum):
    chatgptDeviceCode = 'chatgptDeviceCode'


class LoginAccountParams3(BaseModel):
    type: Type14 = Field(..., title='ChatgptDeviceCodeLoginAccountParamsType')


class Type15(Enum):
    chatgptAuthTokens = 'chatgptAuthTokens'


class LoginAccountParams4(BaseModel):
    accessToken: str = Field(
        ...,
        description='Access token (JWT) supplied by the client. This token is used for backend API requests and email extraction.',
    )
    chatgptAccountId: str = Field(
        ..., description='Workspace/account identifier supplied by the client.'
    )
    chatgptPlanType: str | None = Field(
        None,
        description='Optional plan type supplied by the client.\n\nWhen `null`, Codex attempts to derive the plan type from access-token claims. If unavailable, the plan defaults to `unknown`.',
    )
    type: Type15 = Field(..., title='ChatgptAuthTokensLoginAccountParamsType')


class LoginAccountParams(
    RootModel[
        LoginAccountParams1
        | LoginAccountParams2
        | LoginAccountParams3
        | LoginAccountParams4
    ]
):
    root: (
        LoginAccountParams1
        | LoginAccountParams2
        | LoginAccountParams3
        | LoginAccountParams4
    )


class MarketplaceAddParams(BaseModel):
    refName: str | None = None
    source: str
    sparsePaths: list[str] | None = None


class MarketplaceRemoveParams(BaseModel):
    marketplaceName: str


class MarketplaceUpgradeParams(BaseModel):
    marketplaceName: str | None = None


class McpResourceReadParams(BaseModel):
    server: str
    threadId: str | None = None
    uri: str


class McpServerMigration(BaseModel):
    name: str


class McpServerOauthLoginParams(BaseModel):
    name: str
    scopes: list[str] | None = None
    timeoutSecs: int | None = None


class McpServerStatusDetail(Enum):
    full = 'full'
    toolsAndAuthOnly = 'toolsAndAuthOnly'


class McpServerToolCallParams(BaseModel):
    field_meta: Any | None = Field(None, alias='_meta')
    arguments: Any | None = None
    server: str
    threadId: str
    tool: str


class MergeStrategy(Enum):
    replace = 'replace'
    upsert = 'upsert'


class MessagePhase1(Enum):
    commentary = 'commentary'


class MessagePhase2(Enum):
    final_answer = 'final_answer'


class MessagePhase(RootModel[MessagePhase1 | MessagePhase2]):
    root: MessagePhase1 | MessagePhase2 = Field(
        ...,
        description='Classifies an assistant message as interim commentary or final answer text.\n\nProviders do not emit this consistently, so callers must treat `None` as "phase unknown" and keep compatibility behavior for legacy models.',
    )


class TurnItemsView1(Enum):
    notLoaded = 'notLoaded'


class TurnItemsView2(Enum):
    summary = 'summary'


class TurnItemsView3(Enum):
    full = 'full'


class TurnItemsView(RootModel[TurnItemsView1 | TurnItemsView2 | TurnItemsView3]):
    root: TurnItemsView1 | TurnItemsView2 | TurnItemsView3


class ModeKind(Enum):
    plan = 'plan'
    default = 'default'


class ModelListParams(BaseModel):
    cursor: str | None = Field(
        None, description='Opaque pagination cursor returned by a previous call.'
    )
    includeHidden: bool | None = Field(
        None,
        description='When true, include models that are hidden from the default picker list.',
    )
    limit: conint(ge=0) | None = Field(
        None,
        description='Optional page size; defaults to a reasonable server-side value.',
    )


class ModelProviderCapabilitiesReadParams(BaseModel):
    pass


class NetworkAccess(Enum):
    restricted = 'restricted'
    enabled = 'enabled'


class PermissionProfileListParams(BaseModel):
    cursor: str | None = Field(
        None, description='Opaque pagination cursor returned by a previous call.'
    )
    cwd: str | None = Field(
        None, description='Optional working directory to resolve project config layers.'
    )
    limit: conint(ge=0) | None = Field(
        None, description='Optional page size; defaults to the full result set.'
    )


class Personality(Enum):
    none = 'none'
    friendly = 'friendly'
    pragmatic = 'pragmatic'


class PluginInstallParams(BaseModel):
    marketplacePath: AbsolutePathBuf | None = None
    pluginName: str
    remoteMarketplaceName: str | None = None


class PluginInstalledParams(BaseModel):
    cwds: list[AbsolutePathBuf] | None = Field(
        None,
        description='Optional working directories used to discover repo marketplaces.',
    )
    installSuggestionPluginNames: list[str] | None = Field(
        None,
        description='Additional uninstalled plugin names that should be returned when present locally. This is used by mention surfaces that intentionally expose install entrypoints.',
    )


class PluginListMarketplaceKind(Enum):
    local = 'local'
    vertical = 'vertical'
    workspace_directory = 'workspace-directory'
    shared_with_me = 'shared-with-me'


class PluginListParams(BaseModel):
    cwds: list[AbsolutePathBuf] | None = Field(
        None,
        description='Optional working directories used to discover repo marketplaces. When omitted, only home-scoped marketplaces and the official curated marketplace are considered.',
    )
    marketplaceKinds: list[PluginListMarketplaceKind] | None = Field(
        None,
        description='Optional marketplace kind filter. When omitted, only local marketplaces are queried, plus the default remote catalog when enabled by feature flag.',
    )


class PluginReadParams(BaseModel):
    marketplacePath: AbsolutePathBuf | None = None
    pluginName: str
    remoteMarketplaceName: str | None = None


class PluginShareCheckoutParams(BaseModel):
    remotePluginId: str


class PluginShareDeleteParams(BaseModel):
    remotePluginId: str


class PluginShareDiscoverability(Enum):
    LISTED = 'LISTED'
    UNLISTED = 'UNLISTED'
    PRIVATE = 'PRIVATE'


class PluginShareListParams(BaseModel):
    pass


class PluginSharePrincipalType(Enum):
    user = 'user'
    group = 'group'
    workspace = 'workspace'


class PluginShareTargetRole(Enum):
    reader = 'reader'
    editor = 'editor'


class PluginShareUpdateDiscoverability(Enum):
    UNLISTED = 'UNLISTED'
    PRIVATE = 'PRIVATE'


class PluginSkillReadParams(BaseModel):
    remoteMarketplaceName: str
    remotePluginId: str
    skillName: str


class PluginUninstallParams(BaseModel):
    pluginId: str


class PluginsMigration(BaseModel):
    marketplaceName: str
    pluginNames: list[str]


class TurnInterruptParams(BaseModel):
    threadId: str
    turnId: str


class TurnEnvironmentParams(BaseModel):
    cwd: AbsolutePathBuf
    environmentId: str


class ThreadUnsubscribeParams(BaseModel):
    threadId: str


class ProcessTerminalSize(BaseModel):
    cols: conint(ge=0) = Field(..., description='Terminal width in character cells.')
    rows: conint(ge=0) = Field(..., description='Terminal height in character cells.')


class ThreadUnarchiveParams(BaseModel):
    threadId: str


class RealtimeOutputModality(Enum):
    text = 'text'
    audio = 'audio'


class RealtimeVoice(Enum):
    alloy = 'alloy'
    arbor = 'arbor'
    ash = 'ash'
    ballad = 'ballad'
    breeze = 'breeze'
    cedar = 'cedar'
    coral = 'coral'
    cove = 'cove'
    echo = 'echo'
    ember = 'ember'
    juniper = 'juniper'
    maple = 'maple'
    marin = 'marin'
    sage = 'sage'
    shimmer = 'shimmer'
    sol = 'sol'
    spruce = 'spruce'
    vale = 'vale'
    verse = 'verse'


class ReasoningEffort(Enum):
    none = 'none'
    minimal = 'minimal'
    low = 'low'
    medium = 'medium'
    high = 'high'
    xhigh = 'xhigh'


class Type16(Enum):
    reasoning_text = 'reasoning_text'


class ReasoningItemContent1(BaseModel):
    text: str
    type: Type16 = Field(..., title='ReasoningTextReasoningItemContentType')


class Type17(Enum):
    text = 'text'


class ReasoningItemContent2(BaseModel):
    text: str
    type: Type17 = Field(..., title='TextReasoningItemContentType')


class ReasoningItemContent(RootModel[ReasoningItemContent1 | ReasoningItemContent2]):
    root: ReasoningItemContent1 | ReasoningItemContent2


class Type18(Enum):
    summary_text = 'summary_text'


class ReasoningItemReasoningSummary1(BaseModel):
    text: str
    type: Type18 = Field(..., title='SummaryTextReasoningItemReasoningSummaryType')


class ReasoningItemReasoningSummary(RootModel[ReasoningItemReasoningSummary1]):
    root: ReasoningItemReasoningSummary1


class ReasoningSummary1(Enum):
    auto = 'auto'
    concise = 'concise'
    detailed = 'detailed'


class ReasoningSummary2(Enum):
    none = 'none'


class ReasoningSummary(RootModel[ReasoningSummary1 | ReasoningSummary2]):
    root: ReasoningSummary1 | ReasoningSummary2 = Field(
        ...,
        description="A summary of the reasoning performed by the model. This can be useful for debugging and understanding the model's reasoning process. See https://platform.openai.com/docs/guides/reasoning?api-mode=responses#reasoning-summaries",
    )


class RequestId(RootModel[str | int]):
    root: str | int


class Type19(Enum):
    message = 'message'


class Type20(Enum):
    reasoning = 'reasoning'


class ResponseItem2(BaseModel):
    content: list[ReasoningItemContent] | None = None
    encrypted_content: str | None = None
    summary: list[ReasoningItemReasoningSummary]
    type: Type20 = Field(..., title='ReasoningResponseItemType')


class Type21(Enum):
    local_shell_call = 'local_shell_call'


class ResponseItem3(BaseModel):
    action: LocalShellAction
    call_id: str | None = Field(None, description='Set when using the Responses API.')
    id: str | None = Field(
        None,
        description='Legacy id field retained for compatibility with older payloads.',
    )
    status: LocalShellStatus
    type: Type21 = Field(..., title='LocalShellCallResponseItemType')


class Type22(Enum):
    function_call = 'function_call'


class ResponseItem4(BaseModel):
    arguments: str
    call_id: str
    id: str | None = None
    name: str
    namespace: str | None = None
    type: Type22 = Field(..., title='FunctionCallResponseItemType')


class Type23(Enum):
    tool_search_call = 'tool_search_call'


class ResponseItem5(BaseModel):
    arguments: Any
    call_id: str | None = None
    execution: str
    id: str | None = None
    status: str | None = None
    type: Type23 = Field(..., title='ToolSearchCallResponseItemType')


class Type24(Enum):
    function_call_output = 'function_call_output'


class Type25(Enum):
    custom_tool_call = 'custom_tool_call'


class ResponseItem7(BaseModel):
    call_id: str
    id: str | None = None
    input: str
    name: str
    status: str | None = None
    type: Type25 = Field(..., title='CustomToolCallResponseItemType')


class Type26(Enum):
    custom_tool_call_output = 'custom_tool_call_output'


class Type27(Enum):
    tool_search_output = 'tool_search_output'


class ResponseItem9(BaseModel):
    call_id: str | None = None
    execution: str
    status: str
    tools: list[Any]
    type: Type27 = Field(..., title='ToolSearchOutputResponseItemType')


class Type28(Enum):
    web_search_call = 'web_search_call'


class Type29(Enum):
    image_generation_call = 'image_generation_call'


class ResponseItem11(BaseModel):
    id: str
    result: str
    revised_prompt: str | None = None
    status: str
    type: Type29 = Field(..., title='ImageGenerationCallResponseItemType')


class Type30(Enum):
    compaction = 'compaction'


class ResponseItem12(BaseModel):
    encrypted_content: str
    type: Type30 = Field(..., title='CompactionResponseItemType')


class Type31(Enum):
    compaction_trigger = 'compaction_trigger'


class ResponseItem13(BaseModel):
    type: Type31 = Field(..., title='CompactionTriggerResponseItemType')


class Type32(Enum):
    context_compaction = 'context_compaction'


class ResponseItem14(BaseModel):
    encrypted_content: str | None = None
    type: Type32 = Field(..., title='ContextCompactionResponseItemType')


class Type33(Enum):
    other = 'other'


class ResponseItem15(BaseModel):
    type: Type33 = Field(..., title='OtherResponseItemType')


class Type34(Enum):
    search = 'search'


class ResponsesApiWebSearchAction1(BaseModel):
    queries: list[str] | None = None
    query: str | None = None
    type: Type34 = Field(..., title='SearchResponsesApiWebSearchActionType')


class Type35(Enum):
    open_page = 'open_page'


class ResponsesApiWebSearchAction2(BaseModel):
    type: Type35 = Field(..., title='OpenPageResponsesApiWebSearchActionType')
    url: str | None = None


class Type36(Enum):
    find_in_page = 'find_in_page'


class ResponsesApiWebSearchAction3(BaseModel):
    pattern: str | None = None
    type: Type36 = Field(..., title='FindInPageResponsesApiWebSearchActionType')
    url: str | None = None


class Type37(Enum):
    other = 'other'


class ResponsesApiWebSearchAction4(BaseModel):
    type: Type37 = Field(..., title='OtherResponsesApiWebSearchActionType')


class ResponsesApiWebSearchAction(
    RootModel[
        ResponsesApiWebSearchAction1
        | ResponsesApiWebSearchAction2
        | ResponsesApiWebSearchAction3
        | ResponsesApiWebSearchAction4
    ]
):
    root: (
        ResponsesApiWebSearchAction1
        | ResponsesApiWebSearchAction2
        | ResponsesApiWebSearchAction3
        | ResponsesApiWebSearchAction4
    )


class ReviewDelivery(Enum):
    inline = 'inline'
    detached = 'detached'


class Type38(Enum):
    uncommittedChanges = 'uncommittedChanges'


class ReviewTarget1(BaseModel):
    type: Type38 = Field(..., title='UncommittedChangesReviewTargetType')


class Type39(Enum):
    baseBranch = 'baseBranch'


class ReviewTarget2(BaseModel):
    branch: str
    type: Type39 = Field(..., title='BaseBranchReviewTargetType')


class Type40(Enum):
    commit = 'commit'


class ReviewTarget3(BaseModel):
    sha: str
    title: str | None = Field(
        None,
        description='Optional human-readable label (e.g., commit subject) for UIs.',
    )
    type: Type40 = Field(..., title='CommitReviewTargetType')


class Type41(Enum):
    custom = 'custom'


class ReviewTarget4(BaseModel):
    instructions: str
    type: Type41 = Field(..., title='CustomReviewTargetType')


class ReviewTarget(
    RootModel[ReviewTarget1 | ReviewTarget2 | ReviewTarget3 | ReviewTarget4]
):
    root: ReviewTarget1 | ReviewTarget2 | ReviewTarget3 | ReviewTarget4


class SandboxMode(Enum):
    read_only = 'read-only'
    workspace_write = 'workspace-write'
    danger_full_access = 'danger-full-access'


class Type42(Enum):
    dangerFullAccess = 'dangerFullAccess'


class SandboxPolicy1(BaseModel):
    type: Type42 = Field(..., title='DangerFullAccessSandboxPolicyType')


class Type43(Enum):
    readOnly = 'readOnly'


class SandboxPolicy2(BaseModel):
    networkAccess: bool | None = False
    type: Type43 = Field(..., title='ReadOnlySandboxPolicyType')


class Type44(Enum):
    externalSandbox = 'externalSandbox'


class SandboxPolicy3(BaseModel):
    networkAccess: NetworkAccess | None = 'restricted'
    type: Type44 = Field(..., title='ExternalSandboxSandboxPolicyType')


class Type45(Enum):
    workspaceWrite = 'workspaceWrite'


class SandboxPolicy4(BaseModel):
    excludeSlashTmp: bool | None = False
    excludeTmpdirEnvVar: bool | None = False
    networkAccess: bool | None = False
    type: Type45 = Field(..., title='WorkspaceWriteSandboxPolicyType')
    writableRoots: list[AbsolutePathBuf] | None = Field([], validate_default=True)


class SandboxPolicy(
    RootModel[SandboxPolicy1 | SandboxPolicy2 | SandboxPolicy3 | SandboxPolicy4]
):
    root: SandboxPolicy1 | SandboxPolicy2 | SandboxPolicy3 | SandboxPolicy4


class SendAddCreditsNudgeEmailParams(BaseModel):
    creditType: AddCreditsNudgeCreditType


class SessionMigration(BaseModel):
    cwd: str
    path: str
    title: str | None = None


class Settings(BaseModel):
    developer_instructions: str | None = None
    model: str
    reasoning_effort: ReasoningEffort | None = None


class SkillsConfigWriteParams(BaseModel):
    enabled: bool
    name: str | None = Field(None, description='Name-based selector.')
    path: AbsolutePathBuf | None = Field(None, description='Path-based selector.')


class SkillsListParams(BaseModel):
    cwds: list[str] | None = Field(
        None,
        description='When empty, defaults to the current session working directory.',
    )
    forceReload: bool | None = Field(
        None,
        description='When true, bypass the skills cache and re-scan skills from disk.',
    )


class SortDirection(Enum):
    asc = 'asc'
    desc = 'desc'


class SubagentMigration(BaseModel):
    name: str


class TextElement(BaseModel):
    byteRange: ByteRange = Field(
        ...,
        description='Byte range in the parent `text` buffer that this element occupies.',
    )
    placeholder: str | None = Field(
        None,
        description='Optional human-readable placeholder for the element, displayed in the UI.',
    )


class ThreadApproveGuardianDeniedActionParams(BaseModel):
    event: Any = Field(
        ...,
        description='Serialized `codex_protocol::protocol::GuardianAssessmentEvent`.',
    )
    threadId: str


class ThreadArchiveParams(BaseModel):
    threadId: str


class ThreadResumeParams(BaseModel):
    approvalPolicy: AskForApproval | None = None
    approvalsReviewer: ApprovalsReviewer | None = Field(
        None,
        description='Override where approval requests are routed for review on this thread and subsequent turns.',
    )
    baseInstructions: str | None = None
    config: dict[str, Any] | None = None
    cwd: str | None = None
    developerInstructions: str | None = None
    sandbox: SandboxMode | None = None
    threadId: str
    model: str | None = Field(
        None, description='Configuration overrides for the resumed thread, if any.'
    )
    modelProvider: str | None = None
    personality: Personality | None = None
    serviceTier: str | None = None


class ThreadCompactStartParams(BaseModel):
    threadId: str


class ThreadRollbackParams(BaseModel):
    numTurns: conint(ge=0) = Field(
        ...,
        description="The number of turns to drop from the end of the thread. Must be >= 1.\n\nThis only modifies the thread's history and does not revert local file changes that have been made by the agent. Clients are responsible for reverting these changes.",
    )
    threadId: str


class ThreadGoalClearParams(BaseModel):
    threadId: str


class ThreadGoalGetParams(BaseModel):
    threadId: str


class ThreadGoalStatus(Enum):
    active = 'active'
    paused = 'paused'
    blocked = 'blocked'
    usageLimited = 'usageLimited'
    budgetLimited = 'budgetLimited'
    complete = 'complete'


class ThreadStartSource(Enum):
    startup = 'startup'
    clear = 'clear'


class ThreadInjectItemsParams(BaseModel):
    items: list[Any] = Field(
        ...,
        description="Raw Responses API items to append to the thread's model-visible history.",
    )
    threadId: str


class ThreadListCwdFilter(RootModel[str | list[str]]):
    root: str | list[str]


class ThreadLoadedListParams(BaseModel):
    cursor: str | None = Field(
        None, description='Opaque pagination cursor returned by a previous call.'
    )
    limit: conint(ge=0) | None = Field(
        None, description='Optional page size; defaults to no limit.'
    )


class ThreadMemoryMode(Enum):
    enabled = 'enabled'
    disabled = 'disabled'


class ThreadMetadataGitInfoUpdateParams(BaseModel):
    branch: str | None = Field(
        None,
        description='Omit to leave the stored branch unchanged, set to `null` to clear it, or provide a non-empty string to replace it.',
    )
    originUrl: str | None = Field(
        None,
        description='Omit to leave the stored origin URL unchanged, set to `null` to clear it, or provide a non-empty string to replace it.',
    )
    sha: str | None = Field(
        None,
        description='Omit to leave the stored commit unchanged, set to `null` to clear it, or provide a non-empty string to replace it.',
    )


class ThreadMetadataUpdateParams(BaseModel):
    gitInfo: ThreadMetadataGitInfoUpdateParams | None = Field(
        None,
        description='Patch the stored Git metadata for this thread. Omit a field to leave it unchanged, set it to `null` to clear it, or provide a string to replace the stored value.',
    )
    threadId: str


class ThreadReadParams(BaseModel):
    includeTurns: bool | None = Field(
        False,
        description='When true, include turns and their items from rollout history.',
    )
    threadId: str


class ThreadSourceKind(Enum):
    cli = 'cli'
    vscode = 'vscode'
    exec = 'exec'
    appServer = 'appServer'
    subAgent = 'subAgent'
    subAgentReview = 'subAgentReview'
    subAgentCompact = 'subAgentCompact'
    subAgentThreadSpawn = 'subAgentThreadSpawn'
    subAgentOther = 'subAgentOther'
    unknown = 'unknown'


class ThreadSource(Enum):
    user = 'user'
    subagent = 'subagent'
    memory_consolidation = 'memory_consolidation'


class ThreadRealtimeAudioChunk(BaseModel):
    data: str
    itemId: str | None = None
    numChannels: conint(ge=0)
    sampleRate: conint(ge=0)
    samplesPerChannel: conint(ge=0) | None = None


class ThreadSortKey(Enum):
    created_at = 'created_at'
    updated_at = 'updated_at'


class ThreadShellCommandParams(BaseModel):
    command: str = Field(
        ...,
        description="Shell command string evaluated by the thread's configured shell. Unlike `command/exec`, this intentionally preserves shell syntax such as pipes, redirects, and quoting. This runs unsandboxed with full access rather than inheriting the thread sandbox policy.",
    )
    threadId: str


class Type46(Enum):
    websocket = 'websocket'


class ThreadRealtimeStartTransport1(BaseModel):
    type: Type46 = Field(..., title='WebsocketThreadRealtimeStartTransportType')


class Type47(Enum):
    webrtc = 'webrtc'


class ThreadRealtimeStartTransport2(BaseModel):
    sdp: str = Field(
        ...,
        description='SDP offer generated by a WebRTC RTCPeerConnection after configuring audio and the realtime events data channel.',
    )
    type: Type47 = Field(..., title='WebrtcThreadRealtimeStartTransportType')


class ThreadRealtimeStartTransport(
    RootModel[ThreadRealtimeStartTransport1 | ThreadRealtimeStartTransport2]
):
    root: ThreadRealtimeStartTransport1 | ThreadRealtimeStartTransport2 = Field(
        ..., description='EXPERIMENTAL - transport used by thread realtime.'
    )


class ThreadSetNameParams(BaseModel):
    name: str
    threadId: str


class ClientRequest1(BaseModel):
    id: RequestId
    method: Method = Field(..., title='InitializeRequestMethod')
    params: InitializeParams


class ClientRequest3(BaseModel):
    id: RequestId
    method: Method2 = Field(..., title='Thread/resumeRequestMethod')
    params: ThreadResumeParams


class ClientRequest5(BaseModel):
    id: RequestId
    method: Method4 = Field(..., title='Thread/archiveRequestMethod')
    params: ThreadArchiveParams


class ClientRequest6(BaseModel):
    id: RequestId
    method: Method5 = Field(..., title='Thread/unsubscribeRequestMethod')
    params: ThreadUnsubscribeParams


class ClientRequest7(BaseModel):
    id: RequestId
    method: Method6 = Field(..., title='Thread/name/setRequestMethod')
    params: ThreadSetNameParams


class ClientRequest9(BaseModel):
    id: RequestId
    method: Method8 = Field(..., title='Thread/goal/getRequestMethod')
    params: ThreadGoalGetParams


class ClientRequest10(BaseModel):
    id: RequestId
    method: Method9 = Field(..., title='Thread/goal/clearRequestMethod')
    params: ThreadGoalClearParams


class ClientRequest11(BaseModel):
    id: RequestId
    method: Method10 = Field(..., title='Thread/metadata/updateRequestMethod')
    params: ThreadMetadataUpdateParams


class ClientRequest12(BaseModel):
    id: RequestId
    method: Method11 = Field(..., title='Thread/unarchiveRequestMethod')
    params: ThreadUnarchiveParams


class ClientRequest13(BaseModel):
    id: RequestId
    method: Method12 = Field(..., title='Thread/compact/startRequestMethod')
    params: ThreadCompactStartParams


class ClientRequest14(BaseModel):
    id: RequestId
    method: Method13 = Field(..., title='Thread/shellCommandRequestMethod')
    params: ThreadShellCommandParams


class ClientRequest15(BaseModel):
    id: RequestId
    method: Method14 = Field(
        ..., title='Thread/approveGuardianDeniedActionRequestMethod'
    )
    params: ThreadApproveGuardianDeniedActionParams


class ClientRequest16(BaseModel):
    id: RequestId
    method: Method15 = Field(..., title='Thread/rollbackRequestMethod')
    params: ThreadRollbackParams


class ClientRequest18(BaseModel):
    id: RequestId
    method: Method17 = Field(..., title='Thread/loaded/listRequestMethod')
    params: ThreadLoadedListParams


class ClientRequest19(BaseModel):
    id: RequestId
    method: Method18 = Field(..., title='Thread/readRequestMethod')
    params: ThreadReadParams


class ClientRequest20(BaseModel):
    id: RequestId
    method: Method19 = Field(..., title='Thread/injectItemsRequestMethod')
    params: ThreadInjectItemsParams


class ClientRequest21(BaseModel):
    id: RequestId
    method: Method20 = Field(..., title='Skills/listRequestMethod')
    params: SkillsListParams


class ClientRequest22(BaseModel):
    id: RequestId
    method: Method21 = Field(..., title='Hooks/listRequestMethod')
    params: HooksListParams


class ClientRequest23(BaseModel):
    id: RequestId
    method: Method22 = Field(..., title='Marketplace/addRequestMethod')
    params: MarketplaceAddParams


class ClientRequest24(BaseModel):
    id: RequestId
    method: Method23 = Field(..., title='Marketplace/removeRequestMethod')
    params: MarketplaceRemoveParams


class ClientRequest25(BaseModel):
    id: RequestId
    method: Method24 = Field(..., title='Marketplace/upgradeRequestMethod')
    params: MarketplaceUpgradeParams


class ClientRequest26(BaseModel):
    id: RequestId
    method: Method25 = Field(..., title='Plugin/listRequestMethod')
    params: PluginListParams


class ClientRequest27(BaseModel):
    id: RequestId
    method: Method26 = Field(..., title='Plugin/installedRequestMethod')
    params: PluginInstalledParams


class ClientRequest28(BaseModel):
    id: RequestId
    method: Method27 = Field(..., title='Plugin/readRequestMethod')
    params: PluginReadParams


class ClientRequest29(BaseModel):
    id: RequestId
    method: Method28 = Field(..., title='Plugin/skill/readRequestMethod')
    params: PluginSkillReadParams


class ClientRequest32(BaseModel):
    id: RequestId
    method: Method31 = Field(..., title='Plugin/share/listRequestMethod')
    params: PluginShareListParams


class ClientRequest33(BaseModel):
    id: RequestId
    method: Method32 = Field(..., title='Plugin/share/checkoutRequestMethod')
    params: PluginShareCheckoutParams


class ClientRequest34(BaseModel):
    id: RequestId
    method: Method33 = Field(..., title='Plugin/share/deleteRequestMethod')
    params: PluginShareDeleteParams


class ClientRequest35(BaseModel):
    id: RequestId
    method: Method34 = Field(..., title='App/listRequestMethod')
    params: AppsListParams


class ClientRequest36(BaseModel):
    id: RequestId
    method: Method35 = Field(..., title='Fs/readFileRequestMethod')
    params: FsReadFileParams


class ClientRequest37(BaseModel):
    id: RequestId
    method: Method36 = Field(..., title='Fs/writeFileRequestMethod')
    params: FsWriteFileParams


class ClientRequest38(BaseModel):
    id: RequestId
    method: Method37 = Field(..., title='Fs/createDirectoryRequestMethod')
    params: FsCreateDirectoryParams


class ClientRequest39(BaseModel):
    id: RequestId
    method: Method38 = Field(..., title='Fs/getMetadataRequestMethod')
    params: FsGetMetadataParams


class ClientRequest40(BaseModel):
    id: RequestId
    method: Method39 = Field(..., title='Fs/readDirectoryRequestMethod')
    params: FsReadDirectoryParams


class ClientRequest41(BaseModel):
    id: RequestId
    method: Method40 = Field(..., title='Fs/removeRequestMethod')
    params: FsRemoveParams


class ClientRequest42(BaseModel):
    id: RequestId
    method: Method41 = Field(..., title='Fs/copyRequestMethod')
    params: FsCopyParams


class ClientRequest43(BaseModel):
    id: RequestId
    method: Method42 = Field(..., title='Fs/watchRequestMethod')
    params: FsWatchParams


class ClientRequest44(BaseModel):
    id: RequestId
    method: Method43 = Field(..., title='Fs/unwatchRequestMethod')
    params: FsUnwatchParams


class ClientRequest45(BaseModel):
    id: RequestId
    method: Method44 = Field(..., title='Skills/config/writeRequestMethod')
    params: SkillsConfigWriteParams


class ClientRequest46(BaseModel):
    id: RequestId
    method: Method45 = Field(..., title='Plugin/installRequestMethod')
    params: PluginInstallParams


class ClientRequest47(BaseModel):
    id: RequestId
    method: Method46 = Field(..., title='Plugin/uninstallRequestMethod')
    params: PluginUninstallParams


class ClientRequest50(BaseModel):
    id: RequestId
    method: Method49 = Field(..., title='Turn/interruptRequestMethod')
    params: TurnInterruptParams


class ClientRequest52(BaseModel):
    id: RequestId
    method: Method51 = Field(..., title='Model/listRequestMethod')
    params: ModelListParams


class ClientRequest53(BaseModel):
    id: RequestId
    method: Method52 = Field(..., title='ModelProvider/capabilities/readRequestMethod')
    params: ModelProviderCapabilitiesReadParams


class ClientRequest54(BaseModel):
    id: RequestId
    method: Method53 = Field(..., title='ExperimentalFeature/listRequestMethod')
    params: ExperimentalFeatureListParams


class ClientRequest55(BaseModel):
    id: RequestId
    method: Method54 = Field(..., title='PermissionProfile/listRequestMethod')
    params: PermissionProfileListParams


class ClientRequest56(BaseModel):
    id: RequestId
    method: Method55 = Field(
        ..., title='ExperimentalFeature/enablement/setRequestMethod'
    )
    params: ExperimentalFeatureEnablementSetParams


class ClientRequest57(BaseModel):
    id: RequestId
    method: Method56 = Field(..., title='McpServer/oauth/loginRequestMethod')
    params: McpServerOauthLoginParams


class ClientRequest58(BaseModel):
    id: RequestId
    method: Method57 = Field(..., title='Config/mcpServer/reloadRequestMethod')
    params: None = None


class ClientRequest60(BaseModel):
    id: RequestId
    method: Method59 = Field(..., title='McpServer/resource/readRequestMethod')
    params: McpResourceReadParams


class ClientRequest61(BaseModel):
    id: RequestId
    method: Method60 = Field(..., title='McpServer/tool/callRequestMethod')
    params: McpServerToolCallParams


class ClientRequest63(BaseModel):
    id: RequestId
    method: Method62 = Field(..., title='WindowsSandbox/readinessRequestMethod')
    params: None = None


class ClientRequest64(BaseModel):
    id: RequestId
    method: Method63 = Field(..., title='Account/login/startRequestMethod')
    params: LoginAccountParams


class ClientRequest65(BaseModel):
    id: RequestId
    method: Method64 = Field(..., title='Account/login/cancelRequestMethod')
    params: CancelLoginAccountParams


class ClientRequest66(BaseModel):
    id: RequestId
    method: Method65 = Field(..., title='Account/logoutRequestMethod')
    params: None = None


class ClientRequest67(BaseModel):
    id: RequestId
    method: Method66 = Field(..., title='Account/rateLimits/readRequestMethod')
    params: None = None


class ClientRequest68(BaseModel):
    id: RequestId
    method: Method67 = Field(..., title='Account/sendAddCreditsNudgeEmailRequestMethod')
    params: SendAddCreditsNudgeEmailParams


class ClientRequest69(BaseModel):
    id: RequestId
    method: Method68 = Field(..., title='Feedback/uploadRequestMethod')
    params: FeedbackUploadParams


class ClientRequest71(BaseModel):
    id: RequestId
    method: Method70 = Field(..., title='Command/exec/writeRequestMethod')
    params: CommandExecWriteParams


class ClientRequest72(BaseModel):
    id: RequestId
    method: Method71 = Field(..., title='Command/exec/terminateRequestMethod')
    params: CommandExecTerminateParams


class ClientRequest74(BaseModel):
    id: RequestId
    method: Method73 = Field(..., title='Config/readRequestMethod')
    params: ConfigReadParams


class ClientRequest75(BaseModel):
    id: RequestId
    method: Method74 = Field(..., title='ExternalAgentConfig/detectRequestMethod')
    params: ExternalAgentConfigDetectParams


class ClientRequest79(BaseModel):
    id: RequestId
    method: Method78 = Field(..., title='ConfigRequirements/readRequestMethod')
    params: None = None


class ClientRequest80(BaseModel):
    id: RequestId
    method: Method79 = Field(..., title='Account/readRequestMethod')
    params: GetAccountParams


class ClientRequest81(BaseModel):
    id: RequestId
    method: Method80 = Field(..., title='FuzzyFileSearchRequestMethod')
    params: FuzzyFileSearchParams


class CollaborationMode(BaseModel):
    mode: ModeKind
    settings: Settings


class WindowsSandboxSetupStartParams(BaseModel):
    cwd: AbsolutePathBuf | None = None
    mode: WindowsSandboxSetupMode


class CommandExecParams(BaseModel):
    command: list[str] = Field(
        ..., description='Command argv vector. Empty arrays are rejected.'
    )
    cwd: str | None = Field(
        None, description='Optional working directory. Defaults to the server cwd.'
    )
    disableOutputCap: bool | None = Field(
        None,
        description='Disable stdout/stderr capture truncation for this request.\n\nCannot be combined with `outputBytesCap`.',
    )
    disableTimeout: bool | None = Field(
        None,
        description='Disable the timeout entirely for this request.\n\nCannot be combined with `timeoutMs`.',
    )
    env: dict[str, Any] | None = Field(
        None,
        description='Optional environment overrides merged into the server-computed environment.\n\nMatching names override inherited values. Set a key to `null` to unset an inherited variable.',
    )
    outputBytesCap: conint(ge=0) | None = Field(
        None,
        description='Optional per-stream stdout/stderr capture cap in bytes.\n\nWhen omitted, the server default applies. Cannot be combined with `disableOutputCap`.',
    )
    tty: bool | None = Field(
        None,
        description='Enable PTY mode.\n\nThis implies `streamStdin` and `streamStdoutStderr`.',
    )
    processId: str | None = Field(
        None,
        description='Optional client-supplied, connection-scoped process id.\n\nRequired for `tty`, `streamStdin`, `streamStdoutStderr`, and follow-up `command/exec/write`, `command/exec/resize`, and `command/exec/terminate` calls. When omitted, buffered execution gets an internal id that is not exposed to the client.',
    )
    sandboxPolicy: SandboxPolicy | None = Field(
        None,
        description="Optional sandbox policy for this command.\n\nUses the same shape as thread/turn execution sandbox configuration and defaults to the user's configured policy when omitted. Cannot be combined with `permissionProfile`.",
    )
    size: CommandExecTerminalSize | None = Field(
        None,
        description='Optional initial PTY size in character cells. Only valid when `tty` is true.',
    )
    streamStdin: bool | None = Field(
        None,
        description='Allow follow-up `command/exec/write` requests to write stdin bytes.\n\nRequires a client-supplied `processId`.',
    )
    streamStdoutStderr: bool | None = Field(
        None,
        description='Stream stdout/stderr via `command/exec/outputDelta` notifications.\n\nStreamed bytes are not duplicated into the final response and require a client-supplied `processId`.',
    )
    timeoutMs: int | None = Field(
        None,
        description='Optional timeout in milliseconds.\n\nWhen omitted, the server default applies. Cannot be combined with `disableTimeout`.',
    )


class CommandExecResizeParams(BaseModel):
    processId: str = Field(
        ...,
        description='Client-supplied, connection-scoped `processId` from the original `command/exec` request.',
    )
    size: CommandExecTerminalSize = Field(
        ..., description='New PTY size in character cells.'
    )


class ConfigEdit(BaseModel):
    keyPath: str
    mergeStrategy: MergeStrategy
    value: Any


class ConfigValueWriteParams(BaseModel):
    expectedVersion: str | None = None
    filePath: str | None = Field(
        None,
        description="Path to the config file to write; defaults to the user's `config.toml` when omitted.",
    )
    keyPath: str
    mergeStrategy: MergeStrategy
    value: Any


class ContentItem2(BaseModel):
    detail: ImageDetail | None = None
    image_url: str
    type: Type1 = Field(..., title='InputImageContentItemType')


class ContentItem(RootModel[ContentItem1 | ContentItem2 | ContentItem3]):
    root: ContentItem1 | ContentItem2 | ContentItem3


class FunctionCallOutputContentItem2(BaseModel):
    detail: ImageDetail | None = None
    image_url: str
    type: Type4 = Field(..., title='InputImageFunctionCallOutputContentItemType')


class FunctionCallOutputContentItem(
    RootModel[
        FunctionCallOutputContentItem1
        | FunctionCallOutputContentItem2
        | FunctionCallOutputContentItem3
    ]
):
    root: (
        FunctionCallOutputContentItem1
        | FunctionCallOutputContentItem2
        | FunctionCallOutputContentItem3
    ) = Field(
        ...,
        description='Responses API compatible content items that can be returned by a tool call. This is a subset of ContentItem with the types we support as function call outputs.',
    )


class UserInput1(BaseModel):
    text: str
    text_elements: list[TextElement] | None = Field(
        [],
        description='UI-defined spans within `text` used to render or persist special elements.',
        validate_default=True,
    )
    type: Type6 = Field(..., title='TextUserInputType')


class UserInput2(BaseModel):
    detail: ImageDetail | None = None
    type: Type7 = Field(..., title='ImageUserInputType')
    url: str


class UserInput3(BaseModel):
    detail: ImageDetail | None = None
    path: str
    type: Type8 = Field(..., title='LocalImageUserInputType')


class UserInput(
    RootModel[UserInput1 | UserInput2 | UserInput3 | UserInput4 | UserInput5]
):
    root: UserInput1 | UserInput2 | UserInput3 | UserInput4 | UserInput5


class TurnSteerParams(BaseModel):
    expectedTurnId: str = Field(
        ...,
        description='Required active turn id precondition. The request fails when it does not match the currently active turn.',
    )
    input: list[UserInput]
    threadId: str


class TurnStartParams(BaseModel):
    approvalPolicy: AskForApproval | None = Field(
        None,
        description='Override the approval policy for this turn and subsequent turns.',
    )
    approvalsReviewer: ApprovalsReviewer | None = Field(
        None,
        description='Override where approval requests are routed for review on this turn and subsequent turns.',
    )
    serviceTier: str | None = Field(
        None,
        description='Override the service tier for this turn and subsequent turns.',
    )
    cwd: str | None = Field(
        None,
        description='Override the working directory for this turn and subsequent turns.',
    )
    effort: ReasoningEffort | None = Field(
        None,
        description='Override the reasoning effort for this turn and subsequent turns.',
    )
    sandboxPolicy: SandboxPolicy | None = Field(
        None,
        description='Override the sandbox policy for this turn and subsequent turns.',
    )
    input: list[UserInput]
    model: str | None = Field(
        None, description='Override the model for this turn and subsequent turns.'
    )
    outputSchema: Any | None = Field(
        None,
        description='Optional JSON Schema used to constrain the final assistant message for this turn.',
    )
    threadId: str
    personality: Personality | None = Field(
        None, description='Override the personality for this turn and subsequent turns.'
    )
    summary: ReasoningSummary | None = Field(
        None,
        description='Override the reasoning summary for this turn and subsequent turns.',
    )


class ListMcpServerStatusParams(BaseModel):
    cursor: str | None = Field(
        None, description='Opaque pagination cursor returned by a previous call.'
    )
    detail: McpServerStatusDetail | None = Field(
        None,
        description='Controls how much MCP inventory data to fetch for each server. Defaults to `Full` when omitted.',
    )
    limit: conint(ge=0) | None = Field(
        None, description='Optional page size; defaults to a server-defined value.'
    )


class MigrationDetails(BaseModel):
    commands: list[CommandMigration] | None = Field([], validate_default=True)
    hooks: list[HookMigration] | None = Field([], validate_default=True)
    mcpServers: list[McpServerMigration] | None = Field([], validate_default=True)
    plugins: list[PluginsMigration] | None = Field([], validate_default=True)
    sessions: list[SessionMigration] | None = Field([], validate_default=True)
    subagents: list[SubagentMigration] | None = Field([], validate_default=True)


class PluginShareTarget(BaseModel):
    principalId: str
    principalType: PluginSharePrincipalType
    role: PluginShareTargetRole


class PluginShareUpdateTargetsParams(BaseModel):
    discoverability: PluginShareUpdateDiscoverability
    remotePluginId: str
    shareTargets: list[PluginShareTarget]


class ResponseItem1(BaseModel):
    content: list[ContentItem]
    id: str | None = None
    phase: MessagePhase | None = None
    role: str
    type: Type19 = Field(..., title='MessageResponseItemType')


class ResponseItem10(BaseModel):
    action: ResponsesApiWebSearchAction | None = None
    id: str | None = None
    status: str | None = None
    type: Type28 = Field(..., title='WebSearchCallResponseItemType')


class ReviewStartParams(BaseModel):
    delivery: ReviewDelivery | None = Field(
        None,
        description='Where to run the review: inline (default) on the current thread or detached on a new thread (returned in `reviewThreadId`).',
    )
    target: ReviewTarget
    threadId: str


class ThreadForkParams(BaseModel):
    approvalPolicy: AskForApproval | None = None
    approvalsReviewer: ApprovalsReviewer | None = Field(
        None,
        description='Override where approval requests are routed for review on this thread and subsequent turns.',
    )
    baseInstructions: str | None = None
    config: dict[str, Any] | None = None
    cwd: str | None = None
    developerInstructions: str | None = None
    ephemeral: bool | None = None
    threadSource: ThreadSource | None = Field(
        None,
        description='Optional client-supplied analytics source classification for this forked thread.',
    )
    model: str | None = Field(
        None, description='Configuration overrides for the forked thread, if any.'
    )
    modelProvider: str | None = None
    serviceTier: str | None = None
    threadId: str
    sandbox: SandboxMode | None = None


class ThreadGoalSetParams(BaseModel):
    objective: str | None = None
    status: ThreadGoalStatus | None = None
    threadId: str
    tokenBudget: int | None = None


class ThreadListParams(BaseModel):
    archived: bool | None = Field(
        None,
        description='Optional archived filter; when set to true, only archived threads are returned. If false or null, only non-archived threads are returned.',
    )
    cursor: str | None = Field(
        None, description='Opaque pagination cursor returned by a previous call.'
    )
    cwd: ThreadListCwdFilter | None = Field(
        None,
        description='Optional cwd filter or filters; when set, only threads whose session cwd exactly matches one of these paths are returned.',
    )
    limit: conint(ge=0) | None = Field(
        None,
        description='Optional page size; defaults to a reasonable server-side value.',
    )
    modelProviders: list[str] | None = Field(
        None,
        description='Optional provider filter; when set, only sessions recorded under these providers are returned. When present but empty, includes all providers.',
    )
    searchTerm: str | None = Field(
        None, description='Optional substring filter for the extracted thread title.'
    )
    sortDirection: SortDirection | None = Field(
        None,
        description='Optional sort direction; defaults to descending (newest first).',
    )
    sortKey: ThreadSortKey | None = Field(
        None, description='Optional sort key; defaults to created_at.'
    )
    sourceKinds: list[ThreadSourceKind] | None = Field(
        None,
        description='Optional source filter; when set, only sessions from these source kinds are returned. When omitted or empty, defaults to interactive sources.',
    )
    useStateDbOnly: bool | None = Field(
        None,
        description='If true, return from the state DB without scanning JSONL rollouts to repair thread metadata. Omitted or false preserves scan-and-repair behavior.',
    )


class ThreadStartParams(BaseModel):
    approvalPolicy: AskForApproval | None = None
    approvalsReviewer: ApprovalsReviewer | None = Field(
        None,
        description='Override where approval requests are routed for review on this thread and subsequent turns.',
    )
    baseInstructions: str | None = None
    config: dict[str, Any] | None = None
    cwd: str | None = None
    developerInstructions: str | None = None
    sessionStartSource: ThreadStartSource | None = None
    serviceName: str | None = None
    ephemeral: bool | None = None
    sandbox: SandboxMode | None = None
    personality: Personality | None = None
    model: str | None = None
    modelProvider: str | None = None
    threadSource: ThreadSource | None = Field(
        None,
        description='Optional client-supplied analytics source classification for this thread.',
    )
    serviceTier: str | None = None


class ClientRequest2(BaseModel):
    id: RequestId
    method: Method1 = Field(..., title='Thread/startRequestMethod')
    params: ThreadStartParams


class ClientRequest4(BaseModel):
    id: RequestId
    method: Method3 = Field(..., title='Thread/forkRequestMethod')
    params: ThreadForkParams


class ClientRequest8(BaseModel):
    id: RequestId
    method: Method7 = Field(..., title='Thread/goal/setRequestMethod')
    params: ThreadGoalSetParams


class ClientRequest17(BaseModel):
    id: RequestId
    method: Method16 = Field(..., title='Thread/listRequestMethod')
    params: ThreadListParams


class ClientRequest31(BaseModel):
    id: RequestId
    method: Method30 = Field(..., title='Plugin/share/updateTargetsRequestMethod')
    params: PluginShareUpdateTargetsParams


class ClientRequest48(BaseModel):
    id: RequestId
    method: Method47 = Field(..., title='Turn/startRequestMethod')
    params: TurnStartParams


class ClientRequest49(BaseModel):
    id: RequestId
    method: Method48 = Field(..., title='Turn/steerRequestMethod')
    params: TurnSteerParams


class ClientRequest51(BaseModel):
    id: RequestId
    method: Method50 = Field(..., title='Review/startRequestMethod')
    params: ReviewStartParams


class ClientRequest59(BaseModel):
    id: RequestId
    method: Method58 = Field(..., title='McpServerStatus/listRequestMethod')
    params: ListMcpServerStatusParams


class ClientRequest62(BaseModel):
    id: RequestId
    method: Method61 = Field(..., title='WindowsSandbox/setupStartRequestMethod')
    params: WindowsSandboxSetupStartParams


class ClientRequest70(BaseModel):
    id: RequestId
    method: Method69 = Field(..., title='Command/execRequestMethod')
    params: CommandExecParams


class ClientRequest73(BaseModel):
    id: RequestId
    method: Method72 = Field(..., title='Command/exec/resizeRequestMethod')
    params: CommandExecResizeParams


class ClientRequest77(BaseModel):
    id: RequestId
    method: Method76 = Field(..., title='Config/value/writeRequestMethod')
    params: ConfigValueWriteParams


class ConfigBatchWriteParams(BaseModel):
    edits: list[ConfigEdit]
    expectedVersion: str | None = None
    filePath: str | None = Field(
        None,
        description="Path to the config file to write; defaults to the user's `config.toml` when omitted.",
    )
    reloadUserConfig: bool | None = Field(
        None,
        description='When true, hot-reload the updated user config into all loaded threads after writing.',
    )


class ExternalAgentConfigMigrationItem(BaseModel):
    cwd: str | None = Field(
        None,
        description='Null or empty means home-scoped migration; non-empty means repo-scoped migration.',
    )
    description: str
    details: MigrationDetails | None = None
    itemType: ExternalAgentConfigMigrationItemType


class FunctionCallOutputBody(RootModel[str | list[FunctionCallOutputContentItem]]):
    root: str | list[FunctionCallOutputContentItem]


class PluginShareSaveParams(BaseModel):
    discoverability: PluginShareDiscoverability | None = None
    pluginPath: AbsolutePathBuf
    remotePluginId: str | None = None
    shareTargets: list[PluginShareTarget] | None = None


class ResponseItem6(BaseModel):
    call_id: str
    output: FunctionCallOutputBody
    type: Type24 = Field(..., title='FunctionCallOutputResponseItemType')


class ResponseItem8(BaseModel):
    call_id: str
    name: str | None = None
    output: FunctionCallOutputBody
    type: Type26 = Field(..., title='CustomToolCallOutputResponseItemType')


class ResponseItem(
    RootModel[
        ResponseItem1
        | ResponseItem2
        | ResponseItem3
        | ResponseItem4
        | ResponseItem5
        | ResponseItem6
        | ResponseItem7
        | ResponseItem8
        | ResponseItem9
        | ResponseItem10
        | ResponseItem11
        | ResponseItem12
        | ResponseItem13
        | ResponseItem14
        | ResponseItem15
    ]
):
    root: (
        ResponseItem1
        | ResponseItem2
        | ResponseItem3
        | ResponseItem4
        | ResponseItem5
        | ResponseItem6
        | ResponseItem7
        | ResponseItem8
        | ResponseItem9
        | ResponseItem10
        | ResponseItem11
        | ResponseItem12
        | ResponseItem13
        | ResponseItem14
        | ResponseItem15
    )


class ClientRequest30(BaseModel):
    id: RequestId
    method: Method29 = Field(..., title='Plugin/share/saveRequestMethod')
    params: PluginShareSaveParams


class ClientRequest78(BaseModel):
    id: RequestId
    method: Method77 = Field(..., title='Config/batchWriteRequestMethod')
    params: ConfigBatchWriteParams


class ExternalAgentConfigImportParams(BaseModel):
    migrationItems: list[ExternalAgentConfigMigrationItem]


class ClientRequest76(BaseModel):
    id: RequestId
    method: Method75 = Field(..., title='ExternalAgentConfig/importRequestMethod')
    params: ExternalAgentConfigImportParams


class ClientRequest(
    RootModel[
        ClientRequest1
        | ClientRequest2
        | ClientRequest3
        | ClientRequest4
        | ClientRequest5
        | ClientRequest6
        | ClientRequest7
        | ClientRequest8
        | ClientRequest9
        | ClientRequest10
        | ClientRequest11
        | ClientRequest12
        | ClientRequest13
        | ClientRequest14
        | ClientRequest15
        | ClientRequest16
        | ClientRequest17
        | ClientRequest18
        | ClientRequest19
        | ClientRequest20
        | ClientRequest21
        | ClientRequest22
        | ClientRequest23
        | ClientRequest24
        | ClientRequest25
        | ClientRequest26
        | ClientRequest27
        | ClientRequest28
        | ClientRequest29
        | ClientRequest30
        | ClientRequest31
        | ClientRequest32
        | ClientRequest33
        | ClientRequest34
        | ClientRequest35
        | ClientRequest36
        | ClientRequest37
        | ClientRequest38
        | ClientRequest39
        | ClientRequest40
        | ClientRequest41
        | ClientRequest42
        | ClientRequest43
        | ClientRequest44
        | ClientRequest45
        | ClientRequest46
        | ClientRequest47
        | ClientRequest48
        | ClientRequest49
        | ClientRequest50
        | ClientRequest51
        | ClientRequest52
        | ClientRequest53
        | ClientRequest54
        | ClientRequest55
        | ClientRequest56
        | ClientRequest57
        | ClientRequest58
        | ClientRequest59
        | ClientRequest60
        | ClientRequest61
        | ClientRequest62
        | ClientRequest63
        | ClientRequest64
        | ClientRequest65
        | ClientRequest66
        | ClientRequest67
        | ClientRequest68
        | ClientRequest69
        | ClientRequest70
        | ClientRequest71
        | ClientRequest72
        | ClientRequest73
        | ClientRequest74
        | ClientRequest75
        | ClientRequest76
        | ClientRequest77
        | ClientRequest78
        | ClientRequest79
        | ClientRequest80
        | ClientRequest81
    ]
):
    root: (
        ClientRequest1
        | ClientRequest2
        | ClientRequest3
        | ClientRequest4
        | ClientRequest5
        | ClientRequest6
        | ClientRequest7
        | ClientRequest8
        | ClientRequest9
        | ClientRequest10
        | ClientRequest11
        | ClientRequest12
        | ClientRequest13
        | ClientRequest14
        | ClientRequest15
        | ClientRequest16
        | ClientRequest17
        | ClientRequest18
        | ClientRequest19
        | ClientRequest20
        | ClientRequest21
        | ClientRequest22
        | ClientRequest23
        | ClientRequest24
        | ClientRequest25
        | ClientRequest26
        | ClientRequest27
        | ClientRequest28
        | ClientRequest29
        | ClientRequest30
        | ClientRequest31
        | ClientRequest32
        | ClientRequest33
        | ClientRequest34
        | ClientRequest35
        | ClientRequest36
        | ClientRequest37
        | ClientRequest38
        | ClientRequest39
        | ClientRequest40
        | ClientRequest41
        | ClientRequest42
        | ClientRequest43
        | ClientRequest44
        | ClientRequest45
        | ClientRequest46
        | ClientRequest47
        | ClientRequest48
        | ClientRequest49
        | ClientRequest50
        | ClientRequest51
        | ClientRequest52
        | ClientRequest53
        | ClientRequest54
        | ClientRequest55
        | ClientRequest56
        | ClientRequest57
        | ClientRequest58
        | ClientRequest59
        | ClientRequest60
        | ClientRequest61
        | ClientRequest62
        | ClientRequest63
        | ClientRequest64
        | ClientRequest65
        | ClientRequest66
        | ClientRequest67
        | ClientRequest68
        | ClientRequest69
        | ClientRequest70
        | ClientRequest71
        | ClientRequest72
        | ClientRequest73
        | ClientRequest74
        | ClientRequest75
        | ClientRequest76
        | ClientRequest77
        | ClientRequest78
        | ClientRequest79
        | ClientRequest80
        | ClientRequest81
    ) = Field(
        ..., description='Request from the client to the server.', title='ClientRequest'
    )
