# generated by datamodel-codegen:
#   filename:  CommandExecutionRequestApprovalParams.json
#   timestamp: 2026-05-24T05:49:44+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class AdditionalNetworkPermissions(BaseModel):
    enabled: bool | None = None


class Type(Enum):
    read = 'read'


class CommandAction1(BaseModel):
    command: str
    name: str
    path: AbsolutePathBuf
    type: Type = Field(..., title='ReadCommandActionType')


class Type1(Enum):
    listFiles = 'listFiles'


class CommandAction2(BaseModel):
    command: str
    path: str | None = None
    type: Type1 = Field(..., title='ListFilesCommandActionType')


class Type2(Enum):
    search = 'search'


class CommandAction3(BaseModel):
    command: str
    path: str | None = None
    query: str | None = None
    type: Type2 = Field(..., title='SearchCommandActionType')


class Type3(Enum):
    unknown = 'unknown'


class CommandAction4(BaseModel):
    command: str
    type: Type3 = Field(..., title='UnknownCommandActionType')


class CommandAction(
    RootModel[CommandAction1 | CommandAction2 | CommandAction3 | CommandAction4]
):
    root: CommandAction1 | CommandAction2 | CommandAction3 | CommandAction4


class CommandExecutionApprovalDecision1(Enum):
    accept = 'accept'


class CommandExecutionApprovalDecision2(Enum):
    acceptForSession = 'acceptForSession'


class AcceptWithExecpolicyAmendment(BaseModel):
    execpolicy_amendment: list[str]


class CommandExecutionApprovalDecision3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    acceptWithExecpolicyAmendment: AcceptWithExecpolicyAmendment


class CommandExecutionApprovalDecision5(Enum):
    decline = 'decline'


class CommandExecutionApprovalDecision6(Enum):
    cancel = 'cancel'


class FileSystemAccessMode(Enum):
    read = 'read'
    write = 'write'
    deny = 'deny'


class Type4(Enum):
    path = 'path'


class FileSystemPath1(BaseModel):
    path: AbsolutePathBuf
    type: Type4 = Field(..., title='PathFileSystemPathType')


class Type5(Enum):
    glob_pattern = 'glob_pattern'


class FileSystemPath2(BaseModel):
    pattern: str
    type: Type5 = Field(..., title='GlobPatternFileSystemPathType')


class Type6(Enum):
    special = 'special'


class Kind(Enum):
    root = 'root'


class FileSystemSpecialPath1(BaseModel):
    kind: Kind


class Kind1(Enum):
    minimal = 'minimal'


class FileSystemSpecialPath2(BaseModel):
    kind: Kind1


class Kind2(Enum):
    project_roots = 'project_roots'


class FileSystemSpecialPath3(BaseModel):
    kind: Kind2
    subpath: str | None = None


class Kind3(Enum):
    tmpdir = 'tmpdir'


class FileSystemSpecialPath4(BaseModel):
    kind: Kind3


class Kind4(Enum):
    slash_tmp = 'slash_tmp'


class FileSystemSpecialPath5(BaseModel):
    kind: Kind4


class Kind5(Enum):
    unknown = 'unknown'


class FileSystemSpecialPath6(BaseModel):
    kind: Kind5
    path: str
    subpath: str | None = None


class FileSystemSpecialPath(
    RootModel[
        FileSystemSpecialPath1
        | FileSystemSpecialPath2
        | FileSystemSpecialPath3
        | FileSystemSpecialPath4
        | FileSystemSpecialPath5
        | FileSystemSpecialPath6
    ]
):
    root: (
        FileSystemSpecialPath1
        | FileSystemSpecialPath2
        | FileSystemSpecialPath3
        | FileSystemSpecialPath4
        | FileSystemSpecialPath5
        | FileSystemSpecialPath6
    )


class NetworkApprovalProtocol(Enum):
    http = 'http'
    https = 'https'
    socks5Tcp = 'socks5Tcp'
    socks5Udp = 'socks5Udp'


class NetworkPolicyRuleAction(Enum):
    allow = 'allow'
    deny = 'deny'


class FileSystemPath3(BaseModel):
    type: Type6 = Field(..., title='SpecialFileSystemPathType')
    value: FileSystemSpecialPath


class FileSystemPath(RootModel[FileSystemPath1 | FileSystemPath2 | FileSystemPath3]):
    root: FileSystemPath1 | FileSystemPath2 | FileSystemPath3


class FileSystemSandboxEntry(BaseModel):
    access: FileSystemAccessMode
    path: FileSystemPath


class NetworkApprovalContext(BaseModel):
    host: str
    protocol: NetworkApprovalProtocol


class NetworkPolicyAmendment(BaseModel):
    action: NetworkPolicyRuleAction
    host: str


class CommandExecutionRequestApprovalParams(BaseModel):
    threadId: str
    approvalId: str | None = Field(
        None,
        description='Unique identifier for this specific approval callback.\n\nFor regular shell/unified_exec approvals, this is null.\n\nFor zsh-exec-bridge subcommand approvals, multiple callbacks can belong to one parent `itemId`, so `approvalId` is a distinct opaque callback id (a UUID) used to disambiguate routing.',
    )
    turnId: str
    command: str | None = Field(None, description='The command to be executed.')
    commandActions: list[CommandAction] | None = Field(
        None, description='Best-effort parsed command actions for friendly display.'
    )
    cwd: AbsolutePathBuf | None = Field(
        None, description="The command's working directory."
    )
    itemId: str
    networkApprovalContext: NetworkApprovalContext | None = Field(
        None, description='Optional context for a managed-network approval prompt.'
    )
    proposedExecpolicyAmendment: list[str] | None = Field(
        None,
        description='Optional proposed execpolicy amendment to allow similar commands without prompting.',
    )
    proposedNetworkPolicyAmendments: list[NetworkPolicyAmendment] | None = Field(
        None,
        description='Optional proposed network policy amendments (allow/deny host) for future requests.',
    )
    reason: str | None = Field(
        None,
        description='Optional explanatory reason (e.g. request for network access).',
    )
    startedAtMs: int = Field(
        ...,
        description='Unix timestamp (in milliseconds) when this approval request started.',
    )


class AdditionalFileSystemPermissions(BaseModel):
    entries: list[FileSystemSandboxEntry] | None = None
    globScanMaxDepth: conint(ge=1) | None = None
    read: list[AbsolutePathBuf] | None = Field(
        None, description='This will be removed in favor of `entries`.'
    )
    write: list[AbsolutePathBuf] | None = Field(
        None, description='This will be removed in favor of `entries`.'
    )


class AdditionalPermissionProfile(BaseModel):
    fileSystem: AdditionalFileSystemPermissions | None = None
    network: AdditionalNetworkPermissions | None = Field(
        None, description='Partial overlay used for per-command permission requests.'
    )


class ApplyNetworkPolicyAmendment(BaseModel):
    network_policy_amendment: NetworkPolicyAmendment


class CommandExecutionApprovalDecision4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applyNetworkPolicyAmendment: ApplyNetworkPolicyAmendment


class CommandExecutionApprovalDecision(
    RootModel[
        CommandExecutionApprovalDecision1
        | CommandExecutionApprovalDecision2
        | CommandExecutionApprovalDecision3
        | CommandExecutionApprovalDecision4
        | CommandExecutionApprovalDecision5
        | CommandExecutionApprovalDecision6
    ]
):
    root: (
        CommandExecutionApprovalDecision1
        | CommandExecutionApprovalDecision2
        | CommandExecutionApprovalDecision3
        | CommandExecutionApprovalDecision4
        | CommandExecutionApprovalDecision5
        | CommandExecutionApprovalDecision6
    )
