# generated by datamodel-codegen:
#   filename:  CommandExecutionRequestApprovalResponse.json
#   timestamp: 2026-05-24T05:49:44+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, RootModel


class CommandExecutionApprovalDecision1(Enum):
    accept = 'accept'


class CommandExecutionApprovalDecision2(Enum):
    acceptForSession = 'acceptForSession'


class AcceptWithExecpolicyAmendment(BaseModel):
    execpolicy_amendment: list[str]


class CommandExecutionApprovalDecision3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    acceptWithExecpolicyAmendment: AcceptWithExecpolicyAmendment


class CommandExecutionApprovalDecision5(Enum):
    decline = 'decline'


class CommandExecutionApprovalDecision6(Enum):
    cancel = 'cancel'


class NetworkPolicyRuleAction(Enum):
    allow = 'allow'
    deny = 'deny'


class NetworkPolicyAmendment(BaseModel):
    action: NetworkPolicyRuleAction
    host: str


class ApplyNetworkPolicyAmendment(BaseModel):
    network_policy_amendment: NetworkPolicyAmendment


class CommandExecutionApprovalDecision4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applyNetworkPolicyAmendment: ApplyNetworkPolicyAmendment


class CommandExecutionApprovalDecision(
    RootModel[
        CommandExecutionApprovalDecision1
        | CommandExecutionApprovalDecision2
        | CommandExecutionApprovalDecision3
        | CommandExecutionApprovalDecision4
        | CommandExecutionApprovalDecision5
        | CommandExecutionApprovalDecision6
    ]
):
    root: (
        CommandExecutionApprovalDecision1
        | CommandExecutionApprovalDecision2
        | CommandExecutionApprovalDecision3
        | CommandExecutionApprovalDecision4
        | CommandExecutionApprovalDecision5
        | CommandExecutionApprovalDecision6
    )


class CommandExecutionRequestApprovalResponse(BaseModel):
    decision: CommandExecutionApprovalDecision
