# generated by datamodel-codegen:
#   filename:  components.json
#   timestamp: 2026-05-24T05:49:45+00:00

from __future__ import annotations

from typing import Any

from pydantic import RootModel


class Model(RootModel[Any]):
    root: Any
