# generated by datamodel-codegen:
#   filename:  DynamicToolCallParams.json
#   timestamp: 2026-05-24T05:49:46+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class DynamicToolCallParams(BaseModel):
    arguments: Any
    callId: str
    namespace: str | None = None
    threadId: str
    tool: str
    turnId: str
