# generated by datamodel-codegen:
#   filename:  ExecCommandApprovalParams.json
#   timestamp: 2026-05-24T05:49:48+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class Type(Enum):
    read = 'read'


class ParsedCommand1(BaseModel):
    cmd: str
    name: str
    path: str = Field(
        ...,
        description='(Best effort) Path to the file being read by the command. When possible, this is an absolute path, though when relative, it should be resolved against the `cwd`` that will be used to run the command to derive the absolute path.',
    )
    type: Type = Field(..., title='ReadParsedCommandType')


class Type1(Enum):
    list_files = 'list_files'


class ParsedCommand2(BaseModel):
    cmd: str
    path: str | None = None
    type: Type1 = Field(..., title='ListFilesParsedCommandType')


class Type2(Enum):
    search = 'search'


class ParsedCommand3(BaseModel):
    cmd: str
    path: str | None = None
    query: str | None = None
    type: Type2 = Field(..., title='SearchParsedCommandType')


class Type3(Enum):
    unknown = 'unknown'


class ParsedCommand4(BaseModel):
    cmd: str
    type: Type3 = Field(..., title='UnknownParsedCommandType')


class ParsedCommand(
    RootModel[ParsedCommand1 | ParsedCommand2 | ParsedCommand3 | ParsedCommand4]
):
    root: ParsedCommand1 | ParsedCommand2 | ParsedCommand3 | ParsedCommand4


class ThreadId(RootModel[str]):
    root: str


class ExecCommandApprovalParams(BaseModel):
    approvalId: str | None = Field(
        None, description='Identifier for this specific approval callback.'
    )
    callId: str = Field(
        ...,
        description='Use to correlate this with [codex_protocol::protocol::ExecCommandBeginEvent] and [codex_protocol::protocol::ExecCommandEndEvent].',
    )
    command: list[str]
    conversationId: ThreadId
    cwd: str
    parsedCmd: list[ParsedCommand]
    reason: str | None = None
