# generated by datamodel-codegen:
#   filename:  ExecCommandApprovalResponse.json
#   timestamp: 2026-05-24T05:49:50+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel


class NetworkPolicyRuleAction(Enum):
    allow = 'allow'
    deny = 'deny'


class ReviewDecision1(Enum):
    approved = 'approved'


class ApprovedExecpolicyAmendment(BaseModel):
    proposed_execpolicy_amendment: list[str]


class ReviewDecision2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approved_execpolicy_amendment: ApprovedExecpolicyAmendment


class ReviewDecision3(Enum):
    approved_for_session = 'approved_for_session'


class ReviewDecision5(Enum):
    denied = 'denied'


class ReviewDecision6(Enum):
    timed_out = 'timed_out'


class ReviewDecision7(Enum):
    abort = 'abort'


class NetworkPolicyAmendment(BaseModel):
    action: NetworkPolicyRuleAction
    host: str


class NetworkPolicyAmendment1(BaseModel):
    network_policy_amendment: NetworkPolicyAmendment


class ReviewDecision4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    network_policy_amendment: NetworkPolicyAmendment1


class ReviewDecision(
    RootModel[
        ReviewDecision1
        | ReviewDecision2
        | ReviewDecision3
        | ReviewDecision4
        | ReviewDecision5
        | ReviewDecision6
        | ReviewDecision7
    ]
):
    root: (
        ReviewDecision1
        | ReviewDecision2
        | ReviewDecision3
        | ReviewDecision4
        | ReviewDecision5
        | ReviewDecision6
        | ReviewDecision7
    ) = Field(..., description="User's decision in response to an ExecApprovalRequest.")


class ExecCommandApprovalResponse(BaseModel):
    decision: ReviewDecision
