# generated by datamodel-codegen:
#   filename:  FileChangeRequestApprovalParams.json
#   timestamp: 2026-05-24T05:49:51+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class FileChangeRequestApprovalParams(BaseModel):
    grantRoot: str | None = Field(
        None,
        description='[UNSTABLE] When set, the agent is asking the user to allow writes under this root for the remainder of the session (unclear if this is honored today).',
    )
    itemId: str
    reason: str | None = Field(
        None,
        description='Optional explanatory reason (e.g. request for extra write access).',
    )
    startedAtMs: int = Field(
        ...,
        description='Unix timestamp (in milliseconds) when this approval request started.',
    )
    threadId: str
    turnId: str
