# generated by datamodel-codegen:
#   filename:  FileChangeRequestApprovalResponse.json
#   timestamp: 2026-05-24T05:49:52+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, RootModel


class FileChangeApprovalDecision1(Enum):
    accept = 'accept'


class FileChangeApprovalDecision2(Enum):
    acceptForSession = 'acceptForSession'


class FileChangeApprovalDecision3(Enum):
    decline = 'decline'


class FileChangeApprovalDecision4(Enum):
    cancel = 'cancel'


class FileChangeApprovalDecision(
    RootModel[
        FileChangeApprovalDecision1
        | FileChangeApprovalDecision2
        | FileChangeApprovalDecision3
        | FileChangeApprovalDecision4
    ]
):
    root: (
        FileChangeApprovalDecision1
        | FileChangeApprovalDecision2
        | FileChangeApprovalDecision3
        | FileChangeApprovalDecision4
    )


class FileChangeRequestApprovalResponse(BaseModel):
    decision: FileChangeApprovalDecision
