# generated by datamodel-codegen:
#   filename:  FuzzyFileSearchParams.json
#   timestamp: 2026-05-24T05:49:53+00:00

from __future__ import annotations

from pydantic import BaseModel


class FuzzyFileSearchParams(BaseModel):
    cancellationToken: str | None = None
    query: str
    roots: list[str]
