# generated by datamodel-codegen:
#   filename:  FuzzyFileSearchResponse.json
#   timestamp: 2026-05-24T05:49:54+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, conint


class FuzzyFileSearchMatchType(Enum):
    file = 'file'
    directory = 'directory'


class FuzzyFileSearchResult(BaseModel):
    file_name: str
    indices: list[conint(ge=0)] | None = None
    match_type: FuzzyFileSearchMatchType
    path: str
    root: str
    score: conint(ge=0)


class FuzzyFileSearchResponse(BaseModel):
    files: list[FuzzyFileSearchResult]
