# generated by datamodel-codegen:
#   filename:  FuzzyFileSearchSessionCompletedNotification.json
#   timestamp: 2026-05-24T05:49:55+00:00

from __future__ import annotations

from pydantic import BaseModel


class FuzzyFileSearchSessionCompletedNotification(BaseModel):
    sessionId: str
