# generated by datamodel-codegen:
#   filename:  JSONRPCNotification.json
#   timestamp: 2026-05-24T05:50:00+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class JSONRPCNotification(BaseModel):
    method: str
    params: Any | None = None
