# generated by datamodel-codegen:
#   filename:  JSONRPCErrorError.json
#   timestamp: 2026-05-24T05:49:58+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class JSONRPCErrorError(BaseModel):
    code: int
    data: Any | None = None
    message: str
