# generated by datamodel-codegen:
#   filename:  JSONRPCRequest.json
#   timestamp: 2026-05-24T05:50:01+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, RootModel


class RequestId(RootModel[str | int]):
    root: str | int


class W3cTraceContext(BaseModel):
    traceparent: str | None = None
    tracestate: str | None = None


class JSONRPCRequest(BaseModel):
    id: RequestId
    method: str
    params: Any | None = None
    trace: W3cTraceContext | None = Field(
        None, description='Optional W3C Trace Context for distributed tracing.'
    )
