# generated by datamodel-codegen:
#   filename:  JSONRPCResponse.json
#   timestamp: 2026-05-24T05:50:02+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, RootModel


class RequestId(RootModel[str | int]):
    root: str | int


class JSONRPCResponse(BaseModel):
    id: RequestId
    result: Any
