# generated by datamodel-codegen:
#   filename:  JSONRPCMessage.json
#   timestamp: 2026-05-24T05:49:59+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, RootModel


class JSONRPCErrorError(BaseModel):
    code: int
    data: Any | None = None
    message: str


class JSONRPCNotification(BaseModel):
    method: str
    params: Any | None = None


class RequestId(RootModel[str | int]):
    root: str | int


class W3cTraceContext(BaseModel):
    traceparent: str | None = None
    tracestate: str | None = None


class JSONRPCError(BaseModel):
    error: JSONRPCErrorError
    id: RequestId


class JSONRPCRequest(BaseModel):
    id: RequestId
    method: str
    params: Any | None = None
    trace: W3cTraceContext | None = Field(
        None, description='Optional W3C Trace Context for distributed tracing.'
    )


class JSONRPCResponse(BaseModel):
    id: RequestId
    result: Any


class JSONRPCMessage(
    RootModel[JSONRPCRequest | JSONRPCNotification | JSONRPCResponse | JSONRPCError]
):
    root: JSONRPCRequest | JSONRPCNotification | JSONRPCResponse | JSONRPCError = Field(
        ...,
        description='Refers to any valid JSON-RPC object that can be decoded off the wire, or encoded to be sent.',
        title='JSONRPCMessage',
    )
