# generated by datamodel-codegen:
#   filename:  McpServerElicitationRequestResponse.json
#   timestamp: 2026-05-24T05:50:04+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class McpServerElicitationAction(Enum):
    accept = 'accept'
    decline = 'decline'
    cancel = 'cancel'


class McpServerElicitationRequestResponse(BaseModel):
    field_meta: Any | None = Field(
        None,
        alias='_meta',
        description='Optional client metadata for form-mode action handling.',
    )
    action: McpServerElicitationAction
    content: Any | None = Field(
        None,
        description='Structured user input for accepted elicitations, mirroring RMCP `CreateElicitationResult`.\n\nThis is nullable because decline/cancel responses have no content.',
    )
