# generated by datamodel-codegen:
#   filename:  McpServerElicitationRequestParams.json
#   timestamp: 2026-05-24T05:50:03+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class Mode(Enum):
    form = 'form'


class Mode1(Enum):
    url = 'url'


class McpServerElicitationRequestParams2(BaseModel):
    serverName: str
    threadId: str
    turnId: str | None = Field(
        None,
        description='Active Codex turn when this elicitation was observed, if app-server could correlate one.\n\nThis is nullable because MCP models elicitation as a standalone server-to-client request identified by the MCP server request id. It may be triggered during a turn, but turn context is app-server correlation rather than part of the protocol identity of the elicitation itself.',
    )
    field_meta: Any | None = Field(None, alias='_meta')
    elicitationId: str
    message: str
    mode: Mode1
    url: str


class McpElicitationArrayType(Enum):
    array = 'array'


class McpElicitationBooleanType(Enum):
    boolean = 'boolean'


class McpElicitationConstOption(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    const: str
    title: str


class McpElicitationNumberType(Enum):
    number = 'number'
    integer = 'integer'


class McpElicitationObjectType(Enum):
    object = 'object'


class McpElicitationStringFormat(Enum):
    email = 'email'
    uri = 'uri'
    date = 'date'
    date_time = 'date-time'


class McpElicitationStringType(Enum):
    string = 'string'


class McpElicitationTitledEnumItems(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    anyOf: list[McpElicitationConstOption]


class McpElicitationTitledMultiSelectEnumSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: list[str] | None = None
    description: str | None = None
    items: McpElicitationTitledEnumItems
    maxItems: conint(ge=0) | None = None
    minItems: conint(ge=0) | None = None
    title: str | None = None
    type: McpElicitationArrayType


class McpElicitationTitledSingleSelectEnumSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: str | None = None
    description: str | None = None
    oneOf: list[McpElicitationConstOption]
    title: str | None = None
    type: McpElicitationStringType


class McpElicitationUntitledEnumItems(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enum: list[str]
    type: McpElicitationStringType


class McpElicitationUntitledMultiSelectEnumSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: list[str] | None = None
    description: str | None = None
    items: McpElicitationUntitledEnumItems
    maxItems: conint(ge=0) | None = None
    minItems: conint(ge=0) | None = None
    title: str | None = None
    type: McpElicitationArrayType


class McpElicitationUntitledSingleSelectEnumSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: str | None = None
    description: str | None = None
    enum: list[str]
    title: str | None = None
    type: McpElicitationStringType


class McpElicitationBooleanSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: bool | None = None
    description: str | None = None
    title: str | None = None
    type: McpElicitationBooleanType


class McpElicitationLegacyTitledEnumSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: str | None = None
    description: str | None = None
    enum: list[str]
    enumNames: list[str] | None = None
    title: str | None = None
    type: McpElicitationStringType


class McpElicitationMultiSelectEnumSchema(
    RootModel[
        McpElicitationUntitledMultiSelectEnumSchema
        | McpElicitationTitledMultiSelectEnumSchema
    ]
):
    root: (
        McpElicitationUntitledMultiSelectEnumSchema
        | McpElicitationTitledMultiSelectEnumSchema
    )


class McpElicitationNumberSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: float | None = None
    description: str | None = None
    maximum: float | None = None
    minimum: float | None = None
    title: str | None = None
    type: McpElicitationNumberType


class McpElicitationSingleSelectEnumSchema(
    RootModel[
        McpElicitationUntitledSingleSelectEnumSchema
        | McpElicitationTitledSingleSelectEnumSchema
    ]
):
    root: (
        McpElicitationUntitledSingleSelectEnumSchema
        | McpElicitationTitledSingleSelectEnumSchema
    )


class McpElicitationStringSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: str | None = None
    description: str | None = None
    format: McpElicitationStringFormat | None = None
    maxLength: conint(ge=0) | None = None
    minLength: conint(ge=0) | None = None
    title: str | None = None
    type: McpElicitationStringType


class McpElicitationEnumSchema(
    RootModel[
        McpElicitationSingleSelectEnumSchema
        | McpElicitationMultiSelectEnumSchema
        | McpElicitationLegacyTitledEnumSchema
    ]
):
    root: (
        McpElicitationSingleSelectEnumSchema
        | McpElicitationMultiSelectEnumSchema
        | McpElicitationLegacyTitledEnumSchema
    )


class McpElicitationPrimitiveSchema(
    RootModel[
        McpElicitationEnumSchema
        | McpElicitationStringSchema
        | McpElicitationNumberSchema
        | McpElicitationBooleanSchema
    ]
):
    root: (
        McpElicitationEnumSchema
        | McpElicitationStringSchema
        | McpElicitationNumberSchema
        | McpElicitationBooleanSchema
    )


class McpElicitationSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: str | None = Field(None, alias='$schema')
    properties: dict[str, McpElicitationPrimitiveSchema]
    required: list[str] | None = None
    type: McpElicitationObjectType


class McpServerElicitationRequestParams1(BaseModel):
    serverName: str
    threadId: str
    turnId: str | None = Field(
        None,
        description='Active Codex turn when this elicitation was observed, if app-server could correlate one.\n\nThis is nullable because MCP models elicitation as a standalone server-to-client request identified by the MCP server request id. It may be triggered during a turn, but turn context is app-server correlation rather than part of the protocol identity of the elicitation itself.',
    )
    field_meta: Any | None = Field(None, alias='_meta')
    message: str
    mode: Mode
    requestedSchema: McpElicitationSchema


class McpServerElicitationRequestParams(
    RootModel[McpServerElicitationRequestParams1 | McpServerElicitationRequestParams2]
):
    root: McpServerElicitationRequestParams1 | McpServerElicitationRequestParams2 = (
        Field(..., title='McpServerElicitationRequestParams')
    )
